### ISSUE TITLE
Tests crash on a new solidus project with solidus_starter_frontend and stripe

### ISSUE THREAD

**Issue by abumalick** [solidusio-contrib/solidus_stripe#314]
When I create a new rails project and install solidus with starter and stripe, the tests crash

**Solidus Version**:

4.1.1

**To Reproduce**

```bash
rails new -T amazing_store
cd amazing_store 
bundle add solidus
bin/rails generate solidus:install 
# choose starter and stripe

bundle exec rspec
```

**Current behavior**

I get this error:

```
An error occurred while loading ./spec/system/frontend/solidus_stripe/checkout_spec.rb.
Failure/Error: include SolidusStarterFrontend::System::CheckoutHelpers

NameError:
  uninitialized constant SolidusStarterFrontend::System
# ./spec/support/solidus_stripe/checkout_test_helper.rb:6:in `<module:CheckoutTestHelper>'
# ./spec/support/solidus_stripe/checkout_test_helper.rb:5:in `<main>'
# ./spec/solidus_stripe_spec_helper.rb:6:in `block in <main>'
# ./spec/solidus_stripe_spec_helper.rb:6:in `each'
# ./spec/solidus_stripe_spec_helper.rb:6:in `<main>'
# ./spec/system/frontend/solidus_stripe/checkout_spec.rb:3:in `<main>'
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}


Finished in 0.00004 seconds (files took 4.02 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Expected behavior**

I expect the tests to run (when I choose paypal as payment method it works)

**Screenshots**
<img width="679" alt="image" src="https://github.com/solidusio/solidus_stripe/assets/8377185/33f67fa2-163a-4d95-8d01-be83c2119cfb">

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Browser: N/A
 - Version: N/A

**Additional context**

N/A

**Comment by abumalick** [comment]
A quick fix:
in `spec/support/solidus_stripe/checkout_test_helper.rb`

comment `include SolidusStarterFrontend::System::CheckoutHelpers` and add `include SolidusStarterFrontend::SystemHelpers`.

After that the tests are failing in `spec/system/frontend/solidus_stripe/checkout_spec.rb`. Here are the error messages: 

```
Failures:

  1) SolidusStripe Checkout with a registered user successfully processes payment using available store credits
     Failure/Error: expect(fieldset).to have_css('iframe', wait: 15) # trigger waiting if the frame is not yet there
       expected to find css "iframe" within #<Capybara::Node::Element tag="fieldset" path="/HTML/BODY[1]/MAIN[1]/ARTICLE[1]/DIV[1]/SECTION[1]/FORM[1]/DIV[1]/FIELDSET[1]/UL[1]/LI[1]/FIELDSET[1]"> but there were no matches
     
     [Screenshot Image]: /path/to/project/amazing_store/tmp/capybara/failures_r_spec_example_groups_solidus_stripe_checkout_with_a_registered_user_successfully_processes_payment_using_available_store_credits_538.png

     
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:127:in `find_stripe_iframe'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:108:in `block in fills_in_stripe_input'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:107:in `fills_in_stripe_input'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:91:in `fill_in_stripe_cvc'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:69:in `fill_stripe_form'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:351:in `successfully_creates_a_payment_intent'
     # ./spec/system/frontend/solidus_stripe/checkout_spec.rb:48:in `block (3 levels) in <top (required)>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (3 levels) in <main>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (2 levels) in <main>'

  2) SolidusStripe Checkout with a registered user when setup_future_usage is set with 'on_session' successfully reuses a previously saved card from the user's wallet
     Failure/Error: expect(fieldset).to have_css('iframe', wait: 15) # trigger waiting if the frame is not yet there
       expected to find css "iframe" within #<Capybara::Node::Element tag="fieldset" path="/HTML/BODY[1]/MAIN[1]/ARTICLE[1]/DIV[1]/SECTION[1]/FORM[1]/DIV[1]/FIELDSET[1]/UL[1]/LI[1]/FIELDSET[1]"> but there were no matches
     
     [Screenshot Image]: /path/to/project/amazing_store/tmp/capybara/failures_r_spec_example_groups_solidus_stripe_checkout_with_a_registered_user_when_setup_future_usage_is_set_with_on_session_successfully_reuses_a_previously_saved_card_from_the_user_s_wallet_922.png

     
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:127:in `find_stripe_iframe'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:108:in `block in fills_in_stripe_input'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:107:in `fills_in_stripe_input'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:91:in `fill_in_stripe_cvc'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:69:in `fill_stripe_form'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:351:in `successfully_creates_a_payment_intent'
     # ./spec/system/frontend/solidus_stripe/checkout_spec.rb:59:in `block (5 levels) in <top (required)>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (3 levels) in <main>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (2 levels) in <main>'

  3) SolidusStripe Checkout with a registered user when setup_future_usage is not set requires the user to enter their payment information for each new transaction
     Failure/Error: expect(fieldset).to have_css('iframe', wait: 15) # trigger waiting if the frame is not yet there
       expected to find css "iframe" within #<Capybara::Node::Element tag="fieldset" path="/HTML/BODY[1]/MAIN[1]/ARTICLE[1]/DIV[1]/SECTION[1]/FORM[1]/DIV[1]/FIELDSET[1]/UL[1]/LI[1]/FIELDSET[1]"> but there were no matches
     
     [Screenshot Image]: /path/to/project/amazing_store/tmp/capybara/failures_r_spec_example_groups_solidus_stripe_checkout_with_a_registered_user_when_setup_future_usage_is_not_set_requires_the_user_to_enter_their_payment_information_for_each_new_transaction_644.png

     
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:127:in `find_stripe_iframe'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:108:in `block in fills_in_stripe_input'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:107:in `fills_in_stripe_input'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:91:in `fill_in_stripe_cvc'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:69:in `fill_stripe_form'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:351:in `successfully_creates_a_payment_intent'
     # ./spec/system/frontend/solidus_stripe/checkout_spec.rb:76:in `block (4 levels) in <top (required)>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (3 levels) in <main>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (2 levels) in <main>'

  4) SolidusStripe Checkout with a registered user when setup_future_usage is set with 'off_session' successfully reuses a previously saved card from the user's wallet
     Failure/Error: expect(fieldset).to have_css('iframe', wait: 15) # trigger waiting if the frame is not yet there
       expected to find css "iframe" within #<Capybara::Node::Element tag="fieldset" path="/HTML/BODY[1]/MAIN[1]/ARTICLE[1]/DIV[1]/SECTION[1]/FORM[1]/DIV[1]/FIELDSET[1]/UL[1]/LI[1]/FIELDSET[1]"> but there were no matches
     
     [Screenshot Image]: /path/to/project/amazing_store/tmp/capybara/failures_r_spec_example_groups_solidus_stripe_checkout_with_a_registered_user_when_setup_future_usage_is_set_with_off_session_successfully_reuses_a_previously_saved_card_from_the_user_s_wallet_103.png

     
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:127:in `find_stripe_iframe'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:108:in `block in fills_in_stripe_input'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:107:in `fills_in_stripe_input'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:91:in `fill_in_stripe_cvc'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:69:in `fill_stripe_form'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:351:in `successfully_creates_a_payment_intent'
     # ./spec/system/frontend/solidus_stripe/checkout_spec.rb:59:in `block (5 levels) in <top (required)>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (3 levels) in <main>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (2 levels) in <main>'

  5) SolidusStripe Checkout with declined cards reject transactions with cards declined at intent creation or invalid fields and return an appropriate response
     Failure/Error: expect(fieldset).to have_css('iframe', wait: 15) # trigger waiting if the frame is not yet there
       expected to find css "iframe" within #<Capybara::Node::Element tag="fieldset" path="/HTML/BODY[1]/MAIN[1]/ARTICLE[1]/DIV[1]/SECTION[1]/FORM[1]/DIV[1]/FIELDSET[1]/UL[1]/LI[1]/FIELDSET[1]"> but there were no matches
     
     [Screenshot Image]: /path/to/project/amazing_store/tmp/capybara/failures_r_spec_example_groups_solidus_stripe_checkout_with_declined_cards_reject_transactions_with_cards_declined_at_intent_creation_or_invalid_fields_and_return_an_appropriate_response_164.png

     
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:127:in `find_stripe_iframe'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:96:in `block in fill_in_stripe_country'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:95:in `fill_in_stripe_country'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:285:in `invalid_data_are_notified'
     # ./spec/system/frontend/solidus_stripe/checkout_spec.rb:112:in `block (3 levels) in <top (required)>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (3 levels) in <main>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (2 levels) in <main>'

  6) SolidusStripe Checkout with declined cards with 3D Secure cards reject transaction with failed authentication and return an appropriate response
     Failure/Error: expect(fieldset).to have_css('iframe', wait: 15) # trigger waiting if the frame is not yet there
       expected to find css "iframe" within #<Capybara::Node::Element tag="fieldset" path="/HTML/BODY[1]/MAIN[1]/ARTICLE[1]/DIV[1]/SECTION[1]/FORM[1]/DIV[1]/FIELDSET[1]/UL[1]/LI[1]/FIELDSET[1]"> but there were no matches
     
     [Screenshot Image]: /path/to/project/amazing_store/tmp/capybara/failures_r_spec_example_groups_solidus_stripe_checkout_with_declined_cards_with3_d_secure_cards_reject_transaction_with_failed_authentication_and_return_an_appropriate_response_189.png

     
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:127:in `find_stripe_iframe'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:96:in `block in fill_in_stripe_country'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:95:in `fill_in_stripe_country'
     # ./spec/system/frontend/solidus_stripe/checkout_spec.rb:129:in `block (4 levels) in <top (required)>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (3 levels) in <main>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (2 levels) in <main>'

  7) SolidusStripe Checkout with declined cards with 3D Secure cards processes the transaction with successful authentication
     Failure/Error: expect(fieldset).to have_css('iframe', wait: 15) # trigger waiting if the frame is not yet there
       expected to find css "iframe" within #<Capybara::Node::Element tag="fieldset" path="/HTML/BODY[1]/MAIN[1]/ARTICLE[1]/DIV[1]/SECTION[1]/FORM[1]/DIV[1]/FIELDSET[1]/UL[1]/LI[1]/FIELDSET[1]"> but there were no matches
     
     [Screenshot Image]: /path/to/project/amazing_store/tmp/capybara/failures_r_spec_example_groups_solidus_stripe_checkout_with_declined_cards_with3_d_secure_cards_processes_the_transaction_with_successful_authentication_329.png

     
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:127:in `find_stripe_iframe'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:96:in `block in fill_in_stripe_country'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:95:in `fill_in_stripe_country'
     # ./spec/system/frontend/solidus_stripe/checkout_spec.rb:176:in `block (4 levels) in <top (required)>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (3 levels) in <main>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (2 levels) in <main>'

  8) SolidusStripe Checkout with Stripe Payment Intents and setup_future_usage=on_session creates a payment intent and successfully processes payment
     Failure/Error: expect(fieldset).to have_css('iframe', wait: 15) # trigger waiting if the frame is not yet there
       expected to find css "iframe" within #<Capybara::Node::Element tag="fieldset" path="/HTML/BODY[1]/MAIN[1]/ARTICLE[1]/DIV[1]/SECTION[1]/FORM[1]/DIV[1]/FIELDSET[1]/UL[1]/LI[1]/FIELDSET[1]"> but there were no matches
     
     [Screenshot Image]: /path/to/project/amazing_store/tmp/capybara/failures_r_spec_example_groups_solidus_stripe_checkout_with_stripe_payment_intents_and_setup_future_usage_on_session_creates_a_payment_intent_and_successfully_processes_payment_24.png

     
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:127:in `find_stripe_iframe'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:108:in `block in fills_in_stripe_input'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:107:in `fills_in_stripe_input'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:91:in `fill_in_stripe_cvc'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:69:in `fill_stripe_form'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:351:in `successfully_creates_a_payment_intent'
     # ./spec/system/frontend/solidus_stripe/checkout_spec.rb:17:in `block (4 levels) in <top (required)>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (3 levels) in <main>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (2 levels) in <main>'

  9) SolidusStripe Checkout with Stripe Payment Intents and setup_future_usage=on_session with a guest user creates a payment intent and successfully processes payment
     Failure/Error: expect(fieldset).to have_css('iframe', wait: 15) # trigger waiting if the frame is not yet there
       expected to find css "iframe" within #<Capybara::Node::Element tag="fieldset" path="/HTML/BODY[1]/MAIN[1]/ARTICLE[1]/DIV[1]/SECTION[1]/FORM[1]/DIV[1]/FIELDSET[1]/UL[1]/LI[1]/FIELDSET[1]"> but there were no matches
     
     [Screenshot Image]: /path/to/project/amazing_store/tmp/capybara/failures_r_spec_example_groups_solidus_stripe_checkout_with_stripe_payment_intents_and_setup_future_usage_on_session_with_a_guest_user_creates_a_payment_intent_and_successfully_processes_payment_205.png

     
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:127:in `find_stripe_iframe'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:108:in `block in fills_in_stripe_input'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:107:in `fills_in_stripe_input'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:91:in `fill_in_stripe_cvc'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:69:in `fill_stripe_form'
     # ./spec/support/solidus_stripe/checkout_test_helper.rb:351:in `successfully_creates_a_payment_intent'
     # ./spec/system/frontend/solidus_stripe/checkout_spec.rb:24:in `block (5 levels) in <top (required)>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (3 levels) in <main>'
     # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (2 levels) in <main>'

  10) SolidusStripe Checkout with Stripe Payment Intents and setup_future_usage= creates a payment intent and successfully processes payment
      Failure/Error: expect(fieldset).to have_css('iframe', wait: 15) # trigger waiting if the frame is not yet there
        expected to find css "iframe" within #<Capybara::Node::Element tag="fieldset" path="/HTML/BODY[1]/MAIN[1]/ARTICLE[1]/DIV[1]/SECTION[1]/FORM[1]/DIV[1]/FIELDSET[1]/UL[1]/LI[1]/FIELDSET[1]"> but there were no matches
      
      [Screenshot Image]: /path/to/project/amazing_store/tmp/capybara/failures_r_spec_example_groups_solidus_stripe_checkout_with_stripe_payment_intents_and_setup_future_usage_creates_a_payment_intent_and_successfully_processes_payment_669.png

      
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:127:in `find_stripe_iframe'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:108:in `block in fills_in_stripe_input'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:107:in `fills_in_stripe_input'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:91:in `fill_in_stripe_cvc'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:69:in `fill_stripe_form'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:351:in `successfully_creates_a_payment_intent'
      # ./spec/system/frontend/solidus_stripe/checkout_spec.rb:17:in `block (4 levels) in <top (required)>'
      # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (3 levels) in <main>'
      # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (2 levels) in <main>'

  11) SolidusStripe Checkout with Stripe Payment Intents and setup_future_usage= with a guest user creates a payment intent and successfully processes payment
      Failure/Error: expect(fieldset).to have_css('iframe', wait: 15) # trigger waiting if the frame is not yet there
        expected to find css "iframe" within #<Capybara::Node::Element tag="fieldset" path="/HTML/BODY[1]/MAIN[1]/ARTICLE[1]/DIV[1]/SECTION[1]/FORM[1]/DIV[1]/FIELDSET[1]/UL[1]/LI[1]/FIELDSET[1]"> but there were no matches
      
      [Screenshot Image]: /path/to/project/amazing_store/tmp/capybara/failures_r_spec_example_groups_solidus_stripe_checkout_with_stripe_payment_intents_and_setup_future_usage_with_a_guest_user_creates_a_payment_intent_and_successfully_processes_payment_710.png

      
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:127:in `find_stripe_iframe'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:108:in `block in fills_in_stripe_input'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:107:in `fills_in_stripe_input'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:91:in `fill_in_stripe_cvc'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:69:in `fill_stripe_form'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:351:in `successfully_creates_a_payment_intent'
      # ./spec/system/frontend/solidus_stripe/checkout_spec.rb:24:in `block (5 levels) in <top (required)>'
      # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (3 levels) in <main>'
      # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (2 levels) in <main>'

  12) SolidusStripe Checkout when auto-capture is enabled creates a payment intent and automatically processes payment
      Failure/Error: expect(fieldset).to have_css('iframe', wait: 15) # trigger waiting if the frame is not yet there
        expected to find css "iframe" within #<Capybara::Node::Element tag="fieldset" path="/HTML/BODY[1]/MAIN[1]/ARTICLE[1]/DIV[1]/SECTION[1]/FORM[1]/DIV[1]/FIELDSET[1]/UL[1]/LI[1]/FIELDSET[1]"> but there were no matches
      
      [Screenshot Image]: /path/to/project/amazing_store/tmp/capybara/failures_r_spec_example_groups_solidus_stripe_checkout_when_auto_capture_is_enabled_creates_a_payment_intent_and_automatically_processes_payment_637.png

      
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:127:in `find_stripe_iframe'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:108:in `block in fills_in_stripe_input'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:107:in `fills_in_stripe_input'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:91:in `fill_in_stripe_cvc'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:69:in `fill_stripe_form'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:351:in `successfully_creates_a_payment_intent'
      # ./spec/system/frontend/solidus_stripe/checkout_spec.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (3 levels) in <main>'
      # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (2 levels) in <main>'

  13) SolidusStripe Checkout with Stripe Payment Intents and setup_future_usage=off_session creates a payment intent and successfully processes payment
      Failure/Error: expect(fieldset).to have_css('iframe', wait: 15) # trigger waiting if the frame is not yet there
        expected to find css "iframe" within #<Capybara::Node::Element tag="fieldset" path="/HTML/BODY[1]/MAIN[1]/ARTICLE[1]/DIV[1]/SECTION[1]/FORM[1]/DIV[1]/FIELDSET[1]/UL[1]/LI[1]/FIELDSET[1]"> but there were no matches
      
      [Screenshot Image]: /path/to/project/amazing_store/tmp/capybara/failures_r_spec_example_groups_solidus_stripe_checkout_with_stripe_payment_intents_and_setup_future_usage_off_session_creates_a_payment_intent_and_successfully_processes_payment_236.png

      
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:127:in `find_stripe_iframe'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:108:in `block in fills_in_stripe_input'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:107:in `fills_in_stripe_input'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:91:in `fill_in_stripe_cvc'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:69:in `fill_stripe_form'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:351:in `successfully_creates_a_payment_intent'
      # ./spec/system/frontend/solidus_stripe/checkout_spec.rb:17:in `block (4 levels) in <top (required)>'
      # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (3 levels) in <main>'
      # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (2 levels) in <main>'

  14) SolidusStripe Checkout with Stripe Payment Intents and setup_future_usage=off_session with a guest user creates a payment intent and successfully processes payment
      Failure/Error: expect(fieldset).to have_css('iframe', wait: 15) # trigger waiting if the frame is not yet there
        expected to find css "iframe" within #<Capybara::Node::Element tag="fieldset" path="/HTML/BODY[1]/MAIN[1]/ARTICLE[1]/DIV[1]/SECTION[1]/FORM[1]/DIV[1]/FIELDSET[1]/UL[1]/LI[1]/FIELDSET[1]"> but there were no matches
      
      [Screenshot Image]: /path/to/project/amazing_store/tmp/capybara/failures_r_spec_example_groups_solidus_stripe_checkout_with_stripe_payment_intents_and_setup_future_usage_off_session_with_a_guest_user_creates_a_payment_intent_and_successfully_processes_payment_379.png

      
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:127:in `find_stripe_iframe'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:108:in `block in fills_in_stripe_input'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:107:in `fills_in_stripe_input'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:91:in `fill_in_stripe_cvc'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:69:in `fill_stripe_form'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:351:in `successfully_creates_a_payment_intent'
      # ./spec/system/frontend/solidus_stripe/checkout_spec.rb:24:in `block (5 levels) in <top (required)>'
      # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (3 levels) in <main>'
      # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (2 levels) in <main>'

  15) SolidusStripe Checkout with non-card Stripe payment methods creates a payment intent and successfully processes sepa_debit payment
      Failure/Error: expect(fieldset).to have_css('iframe', wait: 15) # trigger waiting if the frame is not yet there
        expected to find css "iframe" within #<Capybara::Node::Element tag="fieldset" path="/HTML/BODY[1]/MAIN[1]/ARTICLE[1]/DIV[1]/SECTION[1]/FORM[1]/DIV[1]/FIELDSET[1]/UL[1]/LI[1]/FIELDSET[1]"> but there were no matches
      
      [Screenshot Image]: /path/to/project/amazing_store/tmp/capybara/failures_r_spec_example_groups_solidus_stripe_checkout_with_non_card_stripe_payment_methods_creates_a_payment_intent_and_successfully_processes_sepa_debit_payment_109.png

      
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:127:in `find_stripe_iframe'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:191:in `block in choose_stripe_payment_method'
      # ./spec/support/solidus_stripe/checkout_test_helper.rb:190:in `choose_stripe_payment_method'
      # ./spec/system/frontend/solidus_stripe/checkout_spec.rb:94:in `block (3 levels) in <top (required)>'
      # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (3 levels) in <main>'
      # ./spec/support/solidus_starter_frontend/database_cleaner.rb:11:in `block (2 levels) in <main>'

Finished in 3 minutes 56.3 seconds (files took 2.12 seconds to load)
15 examples, 15 failures
```

I don't understand what's the problem right now, so I skipped these tests.
